config/routes.rb
Rails.application.routes.draw do

  get 'acerca_de/index'

  resources :regresion

  resources :estadisticas

  resources :costos_civs
  resources :visados
  resources :honorario_minimos do
    collection do
      get 'buscar_por_costo_proyecto'
      get 'buscar_por_tipo_visado'
    end
  end

  root :to => "home#index"
  devise_for :usuarios, controllers: { registrations: "registrations"}

  resources :usuarios do

    collection do
      get '/', to: 'usuarios#index'
      get 'validar_usuario', to: 'usuarios#validar_usuario'
      get 'validar_mail', to: 'usuarios#validar_mail'
      get '/validar_ci', to: 'usuarios#validar_ci'
      get '/validar_civ', to: 'usuarios#validar_civ'
      get 'validar_mail_v2', to: 'usuarios#validar_mail_v2'
      get '/validar_ci_v2', to: 'usuarios#validar_ci_v2'
      get '/validar_civ_v2', to: 'usuarios#validar_civ_v2'
    end
  end

  

  resources :obras do
    resources :visados
    member do
      get 'readpdf'
      post 'aprobar_obra'
      post 'visar'
      post 'rechazar'
      post 'pagar'
      post 'oceprone'
    end
    collection do
      get 'validar_oceprone'
      get 'aranceles'
      get 'regresion_lineal'
      get 'estadisticas'
      get 'estadistica_aplicada'
    end 
  end

  get 'multifirma', controller: 'obras'
  get 'manual', controller: 'obras'
  get 'pasantes', controller: 'obras'
  get 'irene', controller: 'obras'
  get 'junta', controller: 'obras'
  get 'codigo', controller: 'obras'

  
  resources :area_exteriores do
    collection do
      get 'buscar_por_tipo_area'
    end 
  end 
  
  resources :costos do
    collection do
      get 'buscar_por_descripcion'
    end
  end

  get 'db_backup_restore/backup' 
  get 'db_backup_restore/restore' 

  resources :indice_costos_uso_cats

end

app/models/visado.rb
class Visado < ActiveRecord::Base
  include Filterable
	belongs_to :created_by, class_name: :Usuario
	belongs_to :updated_by, class_name: :Usuario
	belongs_to :obra, class_name: :Obra
  has_many :honorarios_min_distancia_visados
  has_many :honorario_minimos, through: :honorarios_min_distancia_visados

  scope :civ, -> (civ) {joins('JOIN obras ON visados.obra_id = obras.id').joins('JOIN usuarios ON obras.coordinador_proyecto_id = usuarios.id').where('usuarios.civ = ?',civ)}
  scope :tipo, -> (tipo) {where(tipo: tipo)}
  scope :desde, -> (timestamp) { where('created_at >= ?', timestamp) }
  scope :hasta, -> (timestamp) { where('created_at <= ?', timestamp) }
  scope :nombres, -> (nombres) {joins('JOIN obras ON visados.obra_id = obras.id').joins('JOIN usuarios ON obras.coordinador_proyecto_id = usuarios.id').where('usuarios.nombres like ?', '%'+nombres+'%')}


	def honorario_por_repeticion
		if es_repeticion
      if cantidad_repeticiones == 1
        0.60
      elsif cantidad_repeticiones == 2
        1.10
      elsif cantidad_repeticiones == 3
        1.50
      elsif cantidad_repeticiones == 4
        1.80
      elsif cantidad_repeticiones == 5
        2.00
      elsif cantidad_repeticiones == 6
        2.10
      elsif cantidad_repeticiones > 6
        ((cantidad_repeticiones - 6) * 0.10 ) + 2.10
      end
    end
	end
end

app/controllers/visados_controller.rb
class VisadosController < ApplicationController
  before_action :set_visado, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_usuario!

  # GET /visados
  # GET /visados.json
  def index
    @visados_params = parametros_filtro_visado
    @visados = Visado.all.filter(@visados_params)
    authorize @visados
    datos=@visados.select(:tipo).map(&:tipo)
    @moda = datos.mode
  end

  # GET /visados/1
  # GET /visados/1.json
  def show
  end

  # GET /visados/new
  def new
    @visado = Visado.new
  end

  # GET /visados/1/edit
  def edit
  end

  # POST /visados
  # POST /visados.json
  def create
    @visado = Visado.new(visado_params)
    @visado.created_by = @visado.updated_by = current_usuario
    respond_to do |format|
      if @visado.save && @visado.obra.may_procesar? && @visado.obra.procesar!
        format.html { redirect_to @visado, notice: 'Visado was successfully created.' }
        format.json { render :show, status: :created, location: @visado }
      else
        format.html { render :new }
        format.json { render json: @visado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visados/1
  # PATCH/PUT /visados/1.json
  def update
    respond_to do |format|
      if @visado.update(visado_params)
        format.html { redirect_to @visado, notice: 'Visado was successfully updated.' }
        format.json { render :show, status: :ok, location: @visado }
      else
        format.html { render :edit }
        format.json { render json: @visado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visados/1
  # DELETE /visados/1.json
  def destroy
    @visado.destroy
    @obra = @visado.obra
    respond_to do |format|
      format.html { redirect_to @obra, notice: 'Visado se eliminó satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  def honorarios_repeticion
   numero_de_repeticiones = params[:repeticiones]
   @porcentaje = Visado.honorarios_repeticion  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visado
      @visado = Visado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visado_params
      params.fetch(:visado).permit(
        :obra_id, :area_bruta,
        :tipo, :complejidad,
        :costo_construccion_estimado,
        :costo_estimado_proyecto,
        :costo_completo,
        :es_repeticion, 
        :cantidad_repeticiones,
        :costo_completo_repeticion,
        :arancel, :costo_construccion,
        :porcentaje_tabla_datos
        )
    end

    def parametros_filtro_visado
    params.permit(
      :nombres,
      :civ,
      :tipo,
      :desde,
      :hasta,
    )
  end
end

app/views/visados/_form.html.erb
<%= form_for @visado , remote: true do |f| %>
  <% if @visado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visado.errors.count, "error") %> prohibited this visado from being saved:</h2>

      <ul>
      <% @visado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-6 col-md-offset-3">

  
  <div class="form-group">
    <%= f.label :obra %><br>
    <%= f.text_field :obra,  class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo,  class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :area_bruta %><br>
    <%= f.number_field :area_bruta,  class: 'form-control', step: 'any'  %>
  </div>
  <div class="form-group">
    <%= f.label :complejidad %><br>
    <%= f.number_field :complejidad,  class: 'form-control', step: 'any'  %>
  </div>
    <div class="form-group">
    <%= f.label :costo_construccion_estimado %><br>
    <%= f.number_field :costo_construccion_estimado,  class: 'form-control', step: 'any'  %>
  </div>
    <div class="form-group">
    <%= f.label :costo_estimado_proyecto %><br>
    <%= f.number_field :costo_estimado_proyecto,  class: 'form-control', step: 'any'  %>
  </div>
    <div class="form-group">
    <%= f.label :costo_completo %><br>
    <%= f.number_field :costo_completo, class: 'form-control', step: 'any'   %>
  </div>
  <div class="form-group">
    <%= f.label :es_repeticion %><br>
    <%= f.text_field :es_repeticion,  class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cantidad_repeticiones %><br>
    <%= f.number_field :cantidad_repeticiones,  class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :costo_completo_repeticion %><br>
    <%= f.number_field :costo_completo_repeticion,  class: 'form-control', step: 'any'  %>
  </div>
  <div class="form-group">
    <%= f.label :arancel %><br>
    <%= f.number_field :arancel,  class: 'form-control', step: 'any'  %>
  </div>

  </div>
  <center>
  <div class="actions col-md-12">
    <%= f.submit class: 'btn btn-primary'  %>
  </div>
  </center>
</div>
<% end %>

app/views/visados/edit.html.erb
<h1>Editando Visado</h1>

<%= render 'form' %>


<%= link_to 'Back', visados_path, class:'btn btn-primary fa fa-list', style: 'color:white' %>

app/views/visados/index.html.erb
<h3>VISADO</h3>

<%= form_tag(visados_path, method: :get, id: 'visados-filter') do %>
  <table class="col-md-12 text-center table table-striped table-hover">
    <thead>
    <tr>
      <th></th>
      <th  width="13%"><%= select_tag(:tipo,
        options_for_select(TIPOS_VISADO, selected: @visados_params[:tipo]),
        include_blank: 'Tipo',
        class: 'form-control pollito', form: 'visados-filter')%></th>
      <th width="10%"><%= text_field_tag(:nombres, @visados_params[:nombres],
        placeholder: 'Agremiado',
        class: 'form-control pollito',  form: 'visados-filter') %></th>

      <th width="10%"><%= text_field_tag(:civ, @visados_params[:civ],
      placeholder: 'C.I.V',
      class: 'form-control pollito',  form: 'visados-filter') %></th>
      <th></th>

       <th width="14%">
        <span class="col-md-10 pollito">Fecha</span> <span class="fa fa-caret-square-o-down" style="float:right; cursor:pointer" id="date-expand"></span>
        <span class="col-md-12" style="float:left; display:none;" id="date-filter">

          <%= text_field_tag(:desde, @visados_params[:desde],
            placeholder: 'Fecha (desde)',
            class: 'form-control bootstrap-datetimepicker pollito',  form: 'visados-filter') %>

          <%= text_field_tag(:hasta, @visados_params[:hasta],
            placeholder: 'Fecha (hasta)',
            class: 'form-control bootstrap-datetimepicker pollito', form: 'visados-filter') %>
        </span>

      </th>
      <th><%= submit_tag('Filtrar', class: 'btn btn-primary btn-sm', form: 'visados-filter') %></th>

    </tr>

      <tr>
        <th class="text-center">Nombre de obra</th>
        <th class="text-center">Tipo</th>
        <th class="text-center">Coordiandor de Obra </th>
        <th class="text-center">C.I.V</th>
        <th class="text-center">Arancel</th>
        <th class="text-center">Fecha</th>

      </tr>
    </thead>

    <tbody>
      <center>
        <% @visados.each do |visado| %>
          <tr>
          <td><%= visado.obra.nombre %></td>
          <td><%= visado.tipo %></td>
          <td><%= visado.obra.coordinador_proyecto.nombres %> <%= visado.obra.coordinador_proyecto.apellidos %></td>
          <td><%= number_to_currency(visado.obra.coordinador_proyecto.civ, unit: " ", delimiter: ".", separator: ",", precision: 0)%>
          <td><%= number_to_currency(visado.arancel,unit:"Bs.F  ", delimiter: ".", separator: ",")%></td>
          <td><%= ltz(visado.created_at) %></td>
          </tr>
      <% end %>
    </center>
  </tbody>
</table>
  <table class="col-md-12 text-center table table-striped table-hover">
    <thead>
      <tr>
        <th class="text-center"><strong> CANT. VISADOS POR BUSQUEDA:  <%= @visados.distinct.count(:obra_id) %></strong></th>
        <center>
          <th class="text-center"><strong>INGRESOS POR BUSQUEDA:  <%=number_to_currency(@visados.sum(:arancel, :conditions => ["tipo = ?",@visado_params]), unit: "Bs.F   ", precision: 2, delimiter: ".", separator: ",") %>  </strong></th>

        </center>
        <CENTER> 
          <strong> 
            tipo de visado mas realizado: <%= @moda %> 
          </strong>
        </CENTER>
      </tr>
    </thead>
  </table>
  
<% end %>

</table>
<br>

<script>
$('#date-expand').click(function(){
  $('#date-filter').toggle();
});

if ($('#desde').val()!='' ||$('#hasta').val()!=''){
  $('#date-filter').show();
}
$(document).ready(function(){
  var dateTimePickerOptions = {
    format: 'YYYY-MM-DD',
    stepping: 1,
    //useCurrent: false,
    sideBySide: true,
    showClear: true,
    showClose: true,
    showTodayButton: true,
  };
  $('.bootstrap-datetimepicker').datetimepicker(dateTimePickerOptions);
});


</script>

app/views/visados/new.html.erb
<h1>Agregar Visado</h1>

<%= render 'form' %>

app/views/visados/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '', edit_visado_path(@visado), class:'btn btn-primary fa fa-pencil', style: 'color:white' %> |
<%= link_to '', visados_path, class:'btn btn-primary fa fa-list', style: 'color:white' %>