config/routes.rb
Rails.application.routes.draw do

  get 'acerca_de/index'

  resources :regresion

  resources :estadisticas

  resources :costos_civs
  resources :visados
  resources :honorario_minimos do
    collection do
      get 'buscar_por_costo_proyecto'
      get 'buscar_por_tipo_visado'
    end
  end

  root :to => "home#index"
  devise_for :usuarios, controllers: { registrations: "registrations"}

  resources :usuarios do

    collection do
      get '/', to: 'usuarios#index'
      get 'validar_usuario', to: 'usuarios#validar_usuario'
      get 'validar_mail', to: 'usuarios#validar_mail'
      get '/validar_ci', to: 'usuarios#validar_ci'
      get '/validar_civ', to: 'usuarios#validar_civ'
      get 'validar_mail_v2', to: 'usuarios#validar_mail_v2'
      get '/validar_ci_v2', to: 'usuarios#validar_ci_v2'
      get '/validar_civ_v2', to: 'usuarios#validar_civ_v2'
    end
  end

  

  resources :obras do
    resources :visados
    member do
      get 'readpdf'
      post 'aprobar_obra'
      post 'visar'
      post 'rechazar'
      post 'pagar'
      post 'oceprone'
    end
    collection do
      get 'validar_oceprone'
      get 'aranceles'
      get 'regresion_lineal'
      get 'estadisticas'
      get 'estadistica_aplicada'
    end 
  end

  get 'multifirma', controller: 'obras'
  get 'manual', controller: 'obras'
  get 'pasantes', controller: 'obras'
  get 'irene', controller: 'obras'
  get 'junta', controller: 'obras'
  get 'codigo', controller: 'obras'

  
  resources :area_exteriores do
    collection do
      get 'buscar_por_tipo_area'
    end 
  end 
  
  resources :costos do
    collection do
      get 'buscar_por_descripcion'
    end
  end

  get 'db_backup_restore/backup' 
  get 'db_backup_restore/restore' 

  resources :indice_costos_uso_cats

end

app/models/indice_costos_uso_cat.rb
class IndiceCostosUsoCat < ActiveRecord::Base
end

app/controllers/indice_costos_uso_cats_controller.rb
class IndiceCostosUsoCatsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_indice_costos_uso_cat, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_usuario!
  # GET /indice_costos_uso_cats
  # GET /indice_costos_uso_cats.json
  def index
    @indice_costos_uso_cats = IndiceCostosUsoCat.all.order(sort_column+ ' ' + sort_direction)
    authorize @indice_costos_uso_cats
  end

  # GET /indice_costos_uso_cats/1
  # GET /indice_costos_uso_cats/1.json
  def show
  end

  # GET /indice_costos_uso_cats/new
  def new
    @indice_costos_uso_cat = IndiceCostosUsoCat.new
    authorize @indice_costos_uso_cat
  end

  # GET /indice_costos_uso_cats/1/edit
  def edit
  end

  # POST /indice_costos_uso_cats
  # POST /indice_costos_uso_cats.json
  def create
    @indice_costos_uso_cat = IndiceCostosUsoCat.new(indice_costos_uso_cat_params)
    authorize @indice_costos_uso_cat

    respond_to do |format|
      if @indice_costos_uso_cat.save
        format.html { redirect_to indice_costos_uso_cats_path, notice: 'Indice costos por uso y categoría ha sido agregado' }    
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /indice_costos_uso_cats/1
  # PATCH/PUT /indice_costos_uso_cats/1.json
  def update
    authorize @indice_costos_uso_cat
    respond_to do |format|
      if @indice_costos_uso_cat.update(indice_costos_uso_cat_params)
        format.html { redirect_to indice_costos_uso_cats_path, notice: 'Indice costos por uso y categoría fue actualizado.' }
        
      else
        format.html { render :edit }
        format.json { render json: @indice_costos_uso_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indice_costos_uso_cat
      @indice_costos_uso_cat = IndiceCostosUsoCat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indice_costos_uso_cat_params
      params.require(:indice_costos_uso_cat).permit(
      :vivienda_uso,
      :indice_complejidad,   
      :indice_costo,
      )
    end
    def sort_column
      IndiceCostosUsoCat.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/views/indice_costos_uso_cats/_form.html.erb
<%= form_for(@indice_costos_uso_cat) do |f| %>
  <% if @indice_costos_uso_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indice_costos_uso_cat.errors.count, "error") %> prohibited this indice_costos_uso_cat from being saved:</h2>

      <ul>
      <% @indice_costos_uso_cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        <%= f.label :vivienda_uso %><br />
        <%= f.text_field :vivienda_uso,  class: 'form-control', :required => true%>
      </div>

      <div class="form-group">
        <%= f.label :indice_complejidad ,"Índice complejidad %"%><br />
        <%= f.number_field :indice_complejidad,  class: 'form-control', :step => 'any', :required => true%>
      </div>

      <div class="form-group">
        <%= f.label :indice_costo ,"Índice costo Bs.F"%><br />
        <%= f.number_field :indice_costo,  class: 'form-control', :required => true %>
      </div>
  </div>

    <center>
      <div class="actions col-md-12">
        <%= f.submit 'Aceptar', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </center>

<script>
  
$( "#new_indice_costos_uso_cat").validate({
  rules: {
    field: {
      required: true
    }
  }
});

</script>

app/views/indice_costos_uso_cats/edit.html.erb
<h3>EDITAR ÍNDICE DE COSTOS</h3>

<%= render 'form' %>

app/views/indice_costos_uso_cats/index.html.erb
<div class="pull-right"> <%= link_to '', new_indice_costos_uso_cat_path, class:'btn btn-primary fa fa-plus', style: 'color:white' %>
</div>
<h3>ÍNDICE POR CATEGORIAS</h3><br>

<table class="col-md-12 text-center table table-striped table-hover">
  <thead>
    <%= hidden_field_tag :direction, params[:direction]%>
    <%= hidden_field_tag :sort, params[:sort]%>
     <tr>
      <th class="text-center">Uso Vivienda <%= sortable(:vivienda_uso) %></th>
      <th class="text-center">Índice Complejidad <%= sortable(:indice_complejidad) %></th>
      <th class="text-center">Índice Costo <%= sortable(:indice_costo) %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @indice_costos_uso_cats.each do |indice_costos_uso_cat| %>
      <tr>
        <td><%= indice_costos_uso_cat.vivienda_uso.upcase %></td>
        <td><%= number_to_percentage(indice_costos_uso_cat.indice_complejidad, precision: 2, separator: ",") %></td>
        <td><%=number_to_currency(indice_costos_uso_cat.indice_costo, unit:"BsF  ", delimiter: ".", separator: ",") %></td>

        
        <td><%= link_to '', edit_indice_costos_uso_cat_path(indice_costos_uso_cat), class:'btn btn-success fa fa-pencil', style: 'color:white'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/indice_costos_uso_cats/new.html.erb
<h3>INDICE DE COSTOS POR CATEGORÍA</h3>

<%= render 'form' %>