config/routes.rb
Rails.application.routes.draw do

  get 'acerca_de/index'

  resources :regresion

  resources :estadisticas

  resources :costos_civs
  resources :visados
  resources :honorario_minimos do
    collection do
      get 'buscar_por_costo_proyecto'
      get 'buscar_por_tipo_visado'
    end
  end

  root :to => "home#index"
  devise_for :usuarios, controllers: { registrations: "registrations"}

  resources :usuarios do

    collection do
      get '/', to: 'usuarios#index'
      get 'validar_usuario', to: 'usuarios#validar_usuario'
      get 'validar_mail', to: 'usuarios#validar_mail'
      get '/validar_ci', to: 'usuarios#validar_ci'
      get '/validar_civ', to: 'usuarios#validar_civ'
      get 'validar_mail_v2', to: 'usuarios#validar_mail_v2'
      get '/validar_ci_v2', to: 'usuarios#validar_ci_v2'
      get '/validar_civ_v2', to: 'usuarios#validar_civ_v2'
    end
  end

  

  resources :obras do
    resources :visados
    member do
      get 'readpdf'
      post 'aprobar_obra'
      post 'visar'
      post 'rechazar'
      post 'pagar'
      post 'oceprone'
    end
    collection do
      get 'validar_oceprone'
      get 'aranceles'
      get 'regresion_lineal'
      get 'estadisticas'
      get 'estadistica_aplicada'
    end 
  end

  get 'multifirma', controller: 'obras'
  get 'manual', controller: 'obras'
  get 'pasantes', controller: 'obras'
  get 'irene', controller: 'obras'
  get 'junta', controller: 'obras'
  get 'codigo', controller: 'obras'

  
  resources :area_exteriores do
    collection do
      get 'buscar_por_tipo_area'
    end 
  end 
  
  resources :costos do
    collection do
      get 'buscar_por_descripcion'
    end
  end

  get 'db_backup_restore/backup' 
  get 'db_backup_restore/restore' 

  resources :indice_costos_uso_cats

end

app/models/obra.rb
class Obra < ActiveRecord::Base
	include Filterable
	include AASM
	
	belongs_to :coordinador_proyecto, class_name: :Usuario
	has_many :visados, class_name: :Visado

	scope :tipo_obra, -> (tipo) {where(tipo_obra: tipo)}
	scope :uso_obra, -> (uso) {where(uso_obra: uso)}
	scope :nombre, -> (nombre) {where(nombre: nombre)}
	scope :usuario_civ, -> (civ) {joins('JOIN usuarios ON obras.coordinador_proyecto_id = usuarios.id').where('usuarios.civ = ?',civ)}
	scope :municipio_obra, -> (municipio) {where(municipio_obra: municipio)}
	scope :desde, -> (timestamp) { where('obras.created_at >= ?', timestamp) }
	scope :hasta, -> (timestamp) { where('obras.created_at <= ?', timestamp) }
	scope :status_obra, -> (status) {where(status_obra: status)}
	scope :direccion_obra, -> (direccion_obra) {where(direccion_obra: direccion_obra)}

	attr_accessor :file

	aasm :column => 'status_obra' do
    state :creado, :initial => true
    state :pendiente, :en_proceso, :visado, :pagado, :rechazado

    event :aprobar_obra do
      transitions :from => :creado, :to => :pendiente
    end

    event :procesar do
      transitions :from => [:pendiente, :en_proceso], :to => :en_proceso
    end

    event :visar do
      transitions :from => :en_proceso, :to => :visado
    end

    event :pagar do
      transitions :from => :visado, :to => :pagado
    end

    event :rechazar do
      transitions :from => [:pendiente, :en_proceso], :to => :rechazado
    end
  end


end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_obra, only: [:show, :edit, :update, :oceprone, :destroy, :readpdf, :aprobar_obra, :visar, :rechazar, :pagar]
  before_filter :authenticate_usuario!
  RUTA_DIRECTORIO_ARCHIVOS = "public/archivos/"

  # GET /obras
  # GET /obras.json
  def index
    @status_obras = current_usuario.agremiado? ? TIPO_STATUS : TIPO_STATUS - ['creado']
    @obras_params = parametros_filtro_obra
    @obras = policy_scope(Obra).filter(@obras_params).order(sort_column+ ' ' + sort_direction) #tipo_obra(params[:tipo_obra]).uso_obra(params[:uso_obra])
    @usos = UsoConstruccion.all
    authorize @obras 
    @usuario = Usuario.all
    datos= @obras.select(:municipio_obra).map(&:municipio_obra)
    @moda = datos.mode
  end
  

  def aranceles
    @obras_params = parametros_filtro_obra_arancel
    @obras = policy_scope(Obra).filter(@obras_params).where('obras.status_obra = ?', :pagado) #tipo_obra(params[:tipo_obra]).uso_obra(params[:uso_obra])
    @obras = @obras.joins(:visados)
    @total = @obras.sum("visados.arancel")
    @obras = @obras.select("coordinador_proyecto_id, COUNT( distinct (CASE WHEN tipo_obra = 'ANTEPROYECTO' THEN obras.id END)) AS anteproyectos, COUNT(distinct(CASE WHEN tipo_obra = 'PROYECTO' THEN obras.id END)) AS proyectos, SUM(visados.arancel) AS arancel").group('coordinador_proyecto_id')
    authorize @obras 
  end

  def multifirma
     pdf_filename = Rails.root.join "public/parausuarios/multifirma.pdf"
     send_file(pdf_filename.to_s, :filename => "multifirma.pdf", :type => "application/pdf")
  end

  def manual
    send_file(Rails.root.join("public/parausuarios/manual.pdf"), 
      :disposition => "inline", :type => "application/pdf")
  end
  def pasantes
    send_file(Rails.root.join("public/parausuarios/operador.pdf"), 
      :disposition => "inline", :type => "application/pdf")
  end
  def irene
    send_file(Rails.root.join("public/parausuarios/admin.pdf"), 
      :disposition => "inline", :type => "application/pdf")
  end
  def junta
    send_file(Rails.root.join("public/parausuarios/master.pdf"), 
      :disposition => "inline", :type => "application/pdf")
  end
  def codigo
    send_file(Rails.root.join("public/parausuarios/codigo.pdf"), 
      :disposition => "inline", :type => "application/pdf")
  end  
  # GET /obras/1
  # GET /obras/1.json
  def show
    @indice_costos_uso_cats = IndiceCostosUsoCat.all
    @costos = Costo.all
    @cuota_civ = CostosCiv.last.civ
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ObrasPdf.new(@obra, view_context)
        send_data pdf.render, filename: "#{@obra.tipo_obra}_#{@obra.id}.pdf", 
                              type: "application/pdf",
                              disposition: "inline"
      end
    end  

  end

  def readpdf
    send_file(Rails.root.join(@obra.memoria_descriptiva).to_s, 
      :disposition => "inline", :type => "application/pdf")
 end

  # GET /obras/new
  def new
    @obras = policy_scope(Obra).where(status_obra: :pagado).where(tipo_obra: 'ANTEPROYECTO')
    @obra = Obra.new
    authorize @obra
    @usos = UsoConstruccion.all
  end

  # GET /obras/1/edit
  def edit
    @obras = policy_scope(Obra).where(status_obra: :pagado).where(tipo_obra: 'ANTEPROYECTO')
    authorize @obra
    @usos = UsoConstruccion.all
  end

  # POST /obras
  # POST /obras.json
  def create
    @obra = Obra.new(obra_params)
    authorize @obra
    archivo = @obra.file
    nombre_orig = archivo.original_filename
    nombre  = "#{@obra.nombre}-#{Time.zone.now.strftime('%Y%m%d%H%M%S')}.pdf"
    directorio = RUTA_DIRECTORIO_ARCHIVOS
    extension = nombre_orig.slice(nombre_orig.rindex("."), nombre_orig.length).downcase
    if extension == ".pdf"
      path = File.join(directorio, nombre)
      resultado = File.open(path, "wb") { |f| f.write(archivo.read) }
      if resultado
        @obra.memoria_descriptiva = path
      end
    end

    @obra.coordinador_proyecto = current_usuario

    respond_to do |format|
      if @obra.save
        format.html { redirect_to @obra, notice: 'La Obra fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @obra }
      else
        format.html { render :new }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1
  # PATCH/PUT /obras/1.json
  def update
    authorize @obra
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to @obra, notice: 'La obra fue modificata satisfactoriamente.' }
        format.json { render json: @obra, status: :ok, location: @obra }
      else
        format.html { render :edit }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def oceprone
    authorize @obra
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to @obra, notice: 'El numero de expediente ha sido asignado exitosamente.' }
        format.json { render json: @obra, status: :ok, location: @obra }
      else
        format.html { render :edit }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end  
  # DELETE /obras/1
  # DELETE /obras/1.json
  def destroy
    @obra.destroy
    respond_to do |format|
      format.html { redirect_to obras_url, notice: 'La obra fue destruida satisfactoriamente.' }
      format.json { head :no_content }
    end
  end
  def estadisticas
    @obras = Obra.status_obra(:pagado)
    authorize @obras
    datos= @obras.select(:municipio_obra).map(&:municipio_obra)
    @moda = datos.mode
    @obras_mun= @obras.group(:municipio_obra).count
    @ingresos = Visado.joins(:obra).where('obras.status_obra = ?', :pagado).group_by_month('obras.created_at').sum(:arancel)
    @ingresos2 = Visado.joins(:obra).where('obras.status_obra = ?', :pagado).group_by_year('obras.created_at').sum(:arancel)
    
  end
  
  def estadistica_aplicada
    @obras_year= Visado.joins(:obra).where(created_at=""+@año_actual.to_s+"-1-1").group_by_month('obras.created_at').count.to_a.transpose[1]
    @modarep=Obra.status_obra(:pagado).select(:municipio_obra).map(&:municipio_obra)
    @media=@obras_year.mean
    @mediana=@obras_year.median
    @desviacion=@obras_year.standard_deviation
    @varianza=@obras_year.variance
    @moda=@modarep.mode
    
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EstadisticaDescriptiva.new(Time.now.year,@obras_year,view_context,@media,@mediana,@desviacion,@varianza,@moda,current_usuario)
        send_data pdf.render, filename: "Reporte_estadistico "+Time.now.year.to_s+".pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  

  def aprobar_obra
    if @obra.may_aprobar_obra? && @obra.aprobar_obra!
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra fue enviada satisfactoriamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra no pudo ser enviada.' }
        format.json { head :no_content }
      end
    end
  end

  def visar
    if @obra.may_visar? && @obra.visar!
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra fue procesada satisfactoriamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra no pudo ser procesada.' }
        format.json { head :no_content }
      end
    end
  end

  def rechazar
    if @obra.may_rechazar? && @obra.rechazar!
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra fue rechazada.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra no pudo ser rechazada. Intente nuevamente.' }
        format.json { head :no_content }
      end
    end
  end

  def pagar
    if @obra.may_pagar? && @obra.pagar!
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra fue pagada.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @obra, notice: 'La obra no pudo ser pagada. Intente nuevamente.' }
        format.json { head :no_content }
      end
    end
  end


  def validar_oceprone
    obra = Obra.select('n_oceprone').where('n_oceprone =?',params[:obra][:n_oceprone])
    respond_to do |format|
      format.json { render json: !obra.present?}
    end
  end 

  def regresion_lineal
    @obras = Obra.status_obra(:pagado)
    authorize @obras
    @a = 2016
    @b = Time.now.year
    Rails.logger.debug "Current usuario #{current_usuario.inspect}"
    respond_to do |format|
      format.html
      format.pdf do
        pdf = RegresionLineal.new(@obras, @a, @b, view_context, current_usuario)
        send_data pdf.render, filename: "regresion_lineal.pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_obra
    @obra = policy_scope(Obra).find(params[:id])
  end

  def set_visados
    @obra = Obra.find(params[:id]).visados
  end

  def parametros_filtro_obra_arancel
    params.permit(
      :usuario_civ,
      :desde,
      :hasta,
    )
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def obra_params
    params.require(:obra).permit(
      :nombre,
      :propietario_parcela_nombre,
      :propietario_parcela_ci,
      :residente_obra_nombre,
      :residente_obra_civ,
      :direccion_obra,
      :municipio_obra,
      :uso_obra,
      :memoria_descriptiva,
      :n_oceprone,
      :area_parcela,
      :area_bruta_construccion,
      :area_neta_construccion,

app/views/obras/_filter.html.erb
_filter.html.erb

app/views/obras/_nuevo_visado_modal.html.erb
  <!-- Modal -->
<div class="modal nuevo-visado-helper" id="newVisado" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-costos="<%= @costos.to_json %>" data-costos-url="<%= buscar_por_descripcion_costos_url(format: :json)%>" data-exteriores-url="<%= buscar_por_tipo_area_area_exteriores_url(format: :json)%>" data-indice-costos-complejidad="<%=@indice_costos_uso_cats.to_json%>" data-cuota-civ = "<%=@cuota_civ%>" data-honorarios-minimos-costo-url="<%=  buscar_por_costo_proyecto_honorario_minimos_url(format: :json)%>" data-honorarios-url="<%= buscar_por_tipo_visado_honorario_minimos_url(format: :json)%>" data-obra-id="<%= @obra.id%>" data-visados-url="<%= visados_url(format: :json)%>" data-obra-url="<%= obra_url(@obra, format: :json)%>">
 

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">AGREGAR VISADO</h4>
      </div>
      <div class="modal-body">
        <div class="form-group" >
          <label class="">Tipo de Visado</label><br>
          <div class="col-sm-4" style="padding:0">
            <select id="tipo_visado" class="form-control"> 
              <option></option>
              <option>ANTEPROYECTO</option>
              <option>EXTERIORES</option>
              <option>PROYECTO</option>
              <option>URBANISMO</option>
            </select>
          </div>
        </div><br>

        <div class="form-group" id="selector_de_uso"> 
          <label class="">Uso de estructura</label><br>
          <%= select_tag 'indice_costos_complejidad', options_for_select(@indice_costos_uso_cats.collect{ |i| [i.vivienda_uso   ] }),{class: 'form-control', include_blank: ''} %>
        </div>
        <div class="form-group">
          <label>Area Bruta <span class="unidad_distancia"></span>:</label>
          <input type= "text" class="form-control validate-number" id="area_bruta" required minlength="2">
        </div>

        <div class="form-group">
          <label>Indice de complejidad:</label>
          <input class="form-control" id="complejidad" disabled>
        </div>

        <div class="form-group">
          <label>Costo construcción <span class="unidad_monetaria_distancia"></span>:</label>
          <input class="form-control" id="costo_construccion" disabled>
        </div>

        <div class="form-group">
          <label>Costo construcción estimado/BsF:</label>
          <input class="form-control" id="costo_construccion_estimado" disabled>
        </div>

        <div class="form-group exturb" style="display:none" >  
          <table class="table table-striped" >
            <thead><tr>
              <th></th>
              <th>Concepto</th>
              <th>%</th>
            </tr></thead>
            <tbody id="honorarios_minimos">
            </tbody>
          </table>
        </div>
        <div class="form-group proyantep" style="display:none" > 
        <label class="">Honorario minimo</label><br>
        <div class="col-sm-4" style="padding:0">
          <select id="selector_honorario" class="form-control"> 
          </select> 
        </div><br>
        </div>
        
        <div class="form-group">
          <label>Costo estimado proyecto/BsF:</label>
          <input class="form-control" id="costo_estimado_proyecto" disabled>
        </div>

        <div class="form-group">
          <label><span  class="tipo_visado_label"></span>:</label>
          <input class="form-control" id="costo_completo" disabled>
        </div>

        <div class="form-group" style="display:none" id="es_repeticion" > 
          <div class="checkbox">
            <label><input id="pollito" type="checkbox" value="">Es repetición?</label>
          </div>
        </div>

        <div class="cantidad_repeticion form-group" style="display:none">
        <label>Cantidad de repeticiones:</label>
          <input id = "num_repeticiones" class="form-control validate-number"/>
        </div>
       <div class="cantidad_repeticion form-group" style="display:none">
          <label><span  class="tipo_visado_label"></span>:</label>
          <input id = "costo_completo_repeticion" class="form-control" disabled>
        </div>
         <div class="form-group">
          <label>Arancel a pagar/BsF:</label>
          <input class="form-control" id="arancel_de_visado" disabled>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger fa fa-times" data-dismiss="modal" id="cancelar"></button>
        <button type="button" class="btn btn-success fa fa-check" id="guardar"></button>
      </div>
    </div>
  </div>
</div>

app/views/obras/edit.html.erb
<h3>MODIFICAR OBRA</h3>

<%= render 'form' %>

app/views/obras/estadisticas.html.erb
<div>
<center>
	<h3>
		ESTADÍSTICAS DE OBRAS POR MUNICIPIO
	</h3>
</center>
<DIV>
	<CENTER>	
		<%= column_chart @obras_mun,  label: 'Obras Por Este Municipio'%>
	</CENTER>
</DIV>


<center>
	<h3>
		INGRESOS MENSUALES POR VISADO
	</h3>
</center>

<DIV>
	<CENTER>	
		<%= line_chart(@ingresos.each_with_object({}) { |(key, value), hash| hash[key] = value.round(2)},  label: 'Acumulativo de Aranceles Para Este Mes BsF')%>
	</CENTER>
</DIV>

<center>
	<h3>
		INGRESOS ANUALES POR VISADO
	</h3>
</center>

<DIV>
	<CENTER>	
		<%= line_chart(@ingresos2.each_with_object({}) { |(key, value), hash| hash[key] = value.round(2) },  label: 'Acumulativo de Aranceles Para Este Año BsF')%>
	</CENTER>
</DIV>

</div>

app/views/obras/new.html.erb
<h1>NUEVA OBRA</h1>

<%= render 'form' %>
<!--<center>
<div class="col-md-12">	

</div>
</center>-->

app/views/obras/show.html.erb
<div class="col-md-12">
<%if @obra.may_pagar? && policy(@obra).pagar? %>
    <span class="pull-right">&nbsp</span>
    <span><%= button_to  pagar_obra_path(@obra), class: "btn btn-success btn-sm pull-right" do%>
      <span class="fa fa-dollar" style="color:white"></span> Pagar <% end %>
    </span>
  <%end # end if%>
  <%if @obra.may_rechazar? && policy(@obra).rechazar? %>
    <span class="pull-right">&nbsp</span>
    <span><%= button_to  rechazar_obra_path(@obra), class: "btn btn-danger btn-sm pull-right" do%>
      <span class="fa fa-times" style="color:white"></span> Rechazar <% end %>
    </span>
  <%end # end if%>
  <%if @obra.may_visar? && policy(@obra).visar? && @obra.n_oceprone.present? %>
    <span class="pull-right">&nbsp</span>
    <span><%= button_to  visar_obra_path(@obra), class: "btn btn-success btn-sm pull-right" do%>
      <span class="fa fa-check" style="color:white"></span> Procesar  <% end %>
    </span>
  <%end # end if%>
  <% if policy(Visado).create? && (@obra.pendiente? || @obra.en_proceso?) %>
  <span class="pull-right">&nbsp</span>
    <button type="button" class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#newVisado">
      <span class="fa fa-plus"></span> Visado
    </button>
  <%end%>
  <%if @obra.may_aprobar_obra? %>
    <span class="pull-right">&nbsp</span>
    <span><%= button_to  aprobar_obra_obra_path(@obra), class: "btn btn-success btn-sm pull-right" do%>
      <span class="fa fa-check" style="color:white"></span> Aprobar  <% end %>
    </span>
  <%end # end if%>
  
  <%if @obra.creado? && current_usuario.agremiado? %>
  <span class="pull-right">&nbsp</span>
  <span><%= link_to  edit_obra_path(@obra), class: "btn btn-success btn-sm pull-right" do%>
    <span class="fa fa-pencil" style="color:white"></span>  <%end%>
  </span>
  <%end %>
  <% if current_usuario.operador? || current_usuario.system? || current_usuario.admin?%>
  <span class="pull-right">&nbsp</span>
  <span><%= link_to  obra_path(@obra, format: "pdf"), class: "btn btn-success btn-sm pull-right" do%>
    <span class="fa fa-download" style="color:white"></span>  
  <% end %>
  </span>
  <%end%>
  <span class="pull-right">&nbsp</span>
  <span><%= link_to  readpdf_obra_path(@obra), class: "btn btn-danger btn-sm pull-right" do%>
    <span class="fa fa-file-pdf-o" style="color:white"></span>  
  <% end %>
  </span>
  
  
  <div class="col-md-<%if current_usuario.agremiado?%>12<%else%>3<%end%>">

  <h3>DETALLES</h3>
  <strong>OBRA:</strong> <%= @obra.nombre.upcase %><br/>
  <strong>DIRECCIÓN:</strong> <%= @obra.direccion_obra.upcase %><br/>
  <strong>MUNICIPIO:</strong> <%= @obra.municipio_obra.upcase %><br/>
  <strong>PROPIETARIO:</strong> <%= @obra.propietario_parcela_nombre.upcase %><br/>
  <h2><span class="small">VERIFICACIÓN NORMATIVA</span></h2>
  <strong>TIPO DE VISADO:</strong> <%= @obra.tipo_obra.upcase %><br/>
  <strong>ÁREA DE PARCELA Mts2:</strong> <%= number_with_delimiter(@obra.area_parcela,delimiter: ".", separator: ",") %><br/>
  <strong>ÁREA BRUTA DE CONSTRUCCIÓN Mts2:</strong> <%= number_with_delimiter(@obra.area_bruta_construccion,delimiter: ".", separator: ",") %><br/>
  <strong>ÁREA NETA DE CONSTRUCCIÓN Mts2:</strong> <%= number_with_delimiter(@obra.area_neta_construccion,delimiter: ".", separator: ",") %><br/>
  <% if current_usuario.operador? || current_usuario.system? || current_usuario.admin? %>
    <%= form_for @obra, url: oceprone_obra_path(@obra), method: 'post', html: {:class => 'form-inline ocepro-form '} do |f| %>
    <div class="form-group registro-oceprone-helper" data-by-obras-url="<%= validar_oceprone_obras_path(format: :json)%>">
    <label for="numero_ocepro" >N° OCEPRO:</label>
    <input minlength = "5" type="number" id="numero_ocepro" name="obra[n_oceprone]" class="form-control" value="<%=number_with_delimiter(@obra.n_oceprone, delimiter: ".", separator: ",") %>" <%if @obra.n_oceprone.present? %> disabled<%end%> required>
      <% if not @obra.n_oceprone.present? %>
      <button type="submit" class="btn btn-success btn-sm pull-right" id="boton_oceprone" style="color:white" required>
        <span class="fa fa-floppy-o"></span>
      </button>
      <%end%>
    </div>
    <% end  # form end%>
  <%else%>
  <strong>N° OCEPRO:</strong> <%= number_with_delimiter(@obra.n_oceprone, delimiter: ".", separator: ",") %><br/>
  <%if @obra.comentario.present? %>
  <strong>Comentario:</strong> <%= @obra.comentario %><br/>
  <%end%>
  <%end  # if end%>

  </div>
  
  <div class="col-md-9">
  <%if @obra.visados.size > 0 %>
  <h3>VISADOS</h3>
  <table class="col-md-12 text-center table table-striped table-hover">
    <thead>
      <tr>
        <th class="text-center">Tipo</th>
        <th class="text-center">Área bruta Mts2 </th>
        <th class="text-center">Árancel</th>
        <th class="text-center">Creado Por</th>
        <% if policy(Visado).create? && (@obra.pendiente? || @obra.en_proceso?)  %>
        <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <center>
        <% @obra.visados.each do |visado| %>
          <tr>
          <td><%= visado.tipo %></td>
          <td><%= number_with_delimiter(visado.area_bruta, delimiter: ".", separator: ",") %></td>
          <td><%= number_to_currency(visado.arancel, unit: "BsF  ", delimiter: ".", separator: ",")%></td>
          <td><%= visado.created_by.nombres%> <%= visado.created_by.apellidos%></td>
          <% if policy(Visado).create? && (@obra.pendiente? || @obra.en_proceso?) %>
          <td>

            <%= link_to '', obra_visado_path(@obra,visado), class:'btn btn-danger fa fa-trash', style: 'color:white' , method: :delete, data: { confirm: 'Esta seguro?' } %></td><% end %>
          </tr>
        <% end %>
      </center>
    </tbody>
    <tfoot>
    <tr>
    <td colspan="2"><strong>Total a pagar:</strong></td>
    <td><%=  number_to_currency(@obra.visados.sum(:arancel), unit: "BsF  ", delimiter: ".", separator: ",") %></td>
    </tr>
    </tfoot>
  </table>
  <%end%>
   

  <%if !current_usuario.agremiado? %>
  <%= form_for @obra , html: {:class => 'form-inline'} do |f| %>
  <div class="form-group ">
    <textarea required placeholder="Comentario." type="number" id="comentario_obra" style = "resize: none; margin: 0px; width: 400px; height: 50px" maxlength="50" class="form-control"<%if @obra.comentario.present? || current_usuario.agremiado? %> disabled <%end%>><%= @obra.comentario %></textarea>
    <% if not @obra.comentario.present? %>
      <% if current_usuario.operador? || current_usuario.system? || current_usuario.admin? %>
    <button type="button" class="btn btn-primary btn-sm pull-right" id="boton_comentario" style="color:white" required>
      Comentar
    </button>
    <%end%>
    <%end%>
  </div>
  <% end %>
  <%end%>
</div>
  
</div>
<% if policy(Visado).create? %>
<%= render partial:'nuevo_visado_modal' %>
<%end%>