config/routes.rb
Rails.application.routes.draw do

  get 'acerca_de/index'

  resources :regresion

  resources :estadisticas

  resources :costos_civs
  resources :visados
  resources :honorario_minimos do
    collection do
      get 'buscar_por_costo_proyecto'
      get 'buscar_por_tipo_visado'
    end
  end

  root :to => "home#index"
  devise_for :usuarios, controllers: { registrations: "registrations"}

  resources :usuarios do

    collection do
      get '/', to: 'usuarios#index'
      get 'validar_usuario', to: 'usuarios#validar_usuario'
      get 'validar_mail', to: 'usuarios#validar_mail'
      get '/validar_ci', to: 'usuarios#validar_ci'
      get '/validar_civ', to: 'usuarios#validar_civ'
      get 'validar_mail_v2', to: 'usuarios#validar_mail_v2'
      get '/validar_ci_v2', to: 'usuarios#validar_ci_v2'
      get '/validar_civ_v2', to: 'usuarios#validar_civ_v2'
    end
  end

  

  resources :obras do
    resources :visados
    member do
      get 'readpdf'
      post 'aprobar_obra'
      post 'visar'
      post 'rechazar'
      post 'pagar'
      post 'oceprone'
    end
    collection do
      get 'validar_oceprone'
      get 'aranceles'
      get 'regresion_lineal'
      get 'estadisticas'
      get 'estadistica_aplicada'
    end 
  end

  get 'multifirma', controller: 'obras'
  get 'manual', controller: 'obras'
  get 'pasantes', controller: 'obras'
  get 'irene', controller: 'obras'
  get 'junta', controller: 'obras'
  get 'codigo', controller: 'obras'

  
  resources :area_exteriores do
    collection do
      get 'buscar_por_tipo_area'
    end 
  end 
  
  resources :costos do
    collection do
      get 'buscar_por_descripcion'
    end
  end

  get 'db_backup_restore/backup' 
  get 'db_backup_restore/restore' 

  resources :indice_costos_uso_cats

end

app/views/layouts/_flash_messages.html.erb
<% if !flash.empty? %>
<center>
  <% flash.each do |name, msg| -%>
    <p class="alert alert-<%= name.to_s == 'notice' ? 'info' : 'danger' %>">
      <%= msg %>
    </p>
  <% end -%>
</center>

<% end %>

app/views/layouts/_footer.html.erb
<div class="footer text-center">
  <div class="container">
    <p class="text-muted">&copy; Todos los derechos reservados Universidad de Margarita (UNIMAR) 2016.
    </p>
    <center>
	    <div  height="30px" width="20%" style="background-color: white;">
			<%= image_tag "logo-unimar.png",  height: '30' %>
		</div>
	</center>
  </div>
</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Gestor Ciene</title>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>


</head>

app/views/layouts/_nav.html.erb
<div  height="100px" width="100%" style="background-color: white;">
<%= image_tag "logo2.png",  height: '100' %>
<%= image_tag "junta.jpg",  height: '100', align: "right"%>
<img src="/assents/junta.jpg" align="right">
</div>




<!-- Navigation bar -->
<div class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation">
<div  class="banner">

</div>
  <div class="container">
    <div class="navbar-header">
      <%= render 'layouts/nav_header' %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= render(partial: 'layouts/nav_main') %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_user' %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/_nav_header.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

</div>

app/views/layouts/_nav_main.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse" data-no-turbolink>
    <ul class="nav navbar-nav side-nav">
        <% if policy(Obra).index? %>
        <li class="<%= 'active' if current_page?(obras_path) %>" >
            <a href="/obras"><i class="fa fa-fw fa-book"></i> Obras</a>
        </li>
        <% end %>
        <% if policy(Usuario).index? %>
            <li class="<%= 'active' if current_page?(usuarios_path) %>">
                <a href="/usuarios" class="fa fa-user-plus"> Usuarios</a>
            </li>
        <% end %>
        <% if current_usuario.system? || current_usuario.admin? %>
        <li  class="<%= 'active' if current_page?(visados_path) %>" >
            <a href="<%= aranceles_obras_path %>"><i class="fa fa-fw fa-dollar"></i> Aranceles</a>
        </li>
        <%end%>
        <%if current_usuario.system? || current_usuario.admin? %>
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#charts"><i class="fa fa-fw fa-calculator"></i> Estadísticas <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="charts" class="collapse">
                <li>
                    <a href="<%= regresion_lineal_obras_path %>"><i class="fa fa-fw fa-line-chart"> </i> Crecimiento</a>
                </li>
                 <li>
                    <a href="<%= estadisticas_obras_path %>"><i class="fa fa-fw fa-bar-chart-o "> </i> Gráficos</a>
                </li>
                <li>
                    <a href="<%= estadistica_aplicada_obras_path %>"><i class="fa fa-fw fa-search "> </i> Ánalisis Estadístico</a>
                </li>
            </ul>
        </li>
        <%end%>
        <%if  current_usuario.system? || current_usuario.admin? || current_usuario.operador? %>
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#dataload"><i class="fa fa-fw fa-database"></i> Datos <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="dataload" class="<%= (current_page?(honorario_minimos_path) ||
                current_page?(area_exteriores_path) || current_page?(costos_path) || 
                current_page?(indice_costos_uso_cats_path) ) ? 'collapse in' : 'collapse' %> "  >
                <%if current_usuario.system? || current_usuario.admin? || current_usuario.operador?%>
                <li class="<%= 'active2' if current_page?(honorario_minimos_path) %>">
                    <a href="/honorario_minimos">Honorarios mínimo</a>
                </li>
                <%end%>
                <%if current_usuario.system? || current_usuario.admin? || current_usuario.operador?%>
                <li class="<%= 'active2' if current_page?(area_exteriores_path) %>">
                    <a href="/area_exteriores">Áreas externas</a>
                </li>
                <%end%>
                <%if current_usuario.system? || current_usuario.admin?|| current_usuario.operador? %>
                <li class="<%= 'active2' if current_page?(costos_path) %>">
                    <a href="/costos">BsF/Medida</a>
                </li>
                <%end%>
                <%if current_usuario.system?|| current_usuario.admin?|| current_usuario.operador?%>
                <li class="<%= 'active2' if current_page?(indice_costos_uso_cats_path) %>">
                    <a href="/indice_costos_uso_cats">Uso por categoría</a>
                </li>
                <%end%>
                <%if current_usuario.system?|| current_usuario.admin?|| current_usuario.operador?%>
                <li class="<%= 'active2' if current_page?(costos_civs_path) %>">
                    <a href="/costos_civs">U. C.I.V</a>
                </li>
                <%end%>
            </ul>
        </li>
        <%end%>
        <%if current_usuario.system?%>
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#backup"><i class="fa fa-fw fa-database"></i> Respaldos <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="backup" class="collapse">
                <li>
                    <a id="respaldo" src="/db_backup_restore/backup.json">Respaldo</a>
                </li>
                <li>
                    <a id="restaurar">Restaurar</a>
                </li>

            </ul>
        </li>
        <%end%>
        <%if current_usuario.agremiado?%>
        <li>
            <a href="<%= manual_path%>"><i class="fa fa-fw fa-info"></i> Ayuda</a>
        </li>
        <%end%>
         <%if current_usuario.operador?%>
         <li>
            <a href="<%= pasantes_path%>"><i class="fa fa-fw fa-info"></i> Ayuda</a>
        </li>
        <%end%>
         <%if current_usuario.admin?%>
         <li>
            <a href="<%= irene_path%>"><i class="fa fa-fw fa-info"></i> Ayuda</a>
        </li>
        <%end%>
        <%if current_usuario.system?%>
        <li>
            <a href="<%= junta_path%>"><i class="fa fa-fw fa-info"></i> Ayuda</a>
        </li>
        <%end%>
        <%if current_usuario.system?%>
        <li>
            <a href="<%= codigo_path%>"><i class="fa fa-fw fa-info"></i> Codigo</a>
        </li>
        <%end%>
        <li>
            <a href="<%= acerca_de_index_path%>"><i class="fa fa-fw fa-search"></i> Acerca de</a>
        </li>
    </ul>
</div>


app/views/layouts/_nav_user.html.erb
<ul class="nav navbar-right top-nav">
  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_usuario.nombres %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
          <li>
              <a href="/usuarios/edit"><i class="fa fa-fw fa-user"></i> Cuenta</a>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to(destroy_usuario_session_path, :method => :delete) do %> 
              <span class="fa fa-fw fa-power-off"></span>  Salir
            <% end %>
          </li>
      </ul>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <%= render 'layouts/nav_header' %>
    <!-- Top Menu Items -->
    <%= render 'layouts/nav_user' %>
    
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <%= render 'layouts/nav_main' %>
    <!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<%if usuario_signed_in? %>
<body>
<div  class="banner">
<%= link_to "/" do %>
    <%= image_tag "logo.png", height: '100', style: "padding:10px;margin-left:30px"%>
<%end%>
<%= image_tag "junta.png",  height: '120', align: "right", width: "86%" %>
</div>
<div id="wrapper" data-no-turbolink>
    <%= render 'layouts/navbar' %>
    
    <div id="page-wrapper">
        <div class="container-fluid" style="min-height:400px">
        <%= render 'layouts/flash_messages' %>
            <div class="row">
            <!-- yield... -->
            <%= yield %>
            <!-- ...yield -->
            </div>
            <%= render 'layouts/footer' %>
        </div>
    </div>

</div>
</body>
<% else %>
<body class="bg-img">
<div style="position:absolute;top:10px;width:100%">
<%= render 'layouts/flash_messages' %>

</div>
    <div class="container-fluid" style="min-height:400px">
    <%= yield %>
    </div>

</body>

<% end %>     

<% if flash.present? %>
<script >
setTimeout( "$('.alert').fadeOut(1500);",3000 );
</script>
<% end %>
   















</html